# Generated by Django 3.0.5 on 2020-04-21 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tcas', '0004_auto_20200420_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='team_count_primary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='team_count_secondary',
            field=models.IntegerField(default=0),
        ),
    ]
