# Generated by Django 3.0.5 on 2020-04-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcas', '0006_auto_20200421_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='form_method',
            field=models.SmallIntegerField(null=True),
        ),
    ]
