# Generated by Django 3.0.5 on 2020-04-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcas', '0007_auto_20200427_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='leader_bonus',
            field=models.SmallIntegerField(default=0),
        ),
    ]
