# Generated by Django 3.0.5 on 2020-04-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcas', '0008_auto_20200429_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
