# Generated by Django 3.0.5 on 2020-04-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcas', '0009_auto_20200430_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
