# Generated by Django 3.0.5 on 2020-05-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcas', '0010_auto_20200430_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_generated',
        ),
    ]
