# Generated by Django 3.0.5 on 2020-05-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcas', '0011_remove_team_is_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
