# Generated by Django 3.0.5 on 2020-05-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcas', '0012_course_is_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
